### ISSUE TITLE
Heroku load order bug

### ISSUE THREAD

**Issue by mokolabs** [shuber/sortable#5]
Due to a load order issue, sortable will break when deployed to Heroku (running Ruby 1.8.7).

As a work around, add this code to your model, just _above_ the sortable method, like so:

```
# Heroku hack to fix load order issue with sortable plugin
self.column_names

sortable :scope => :theater_id, :column => :theater_gallery, :list_name => :theater_gallery
```

Shout out to my buddy @merbist for this fix!

**Comment by mattetti** [comment]
To be a tiny bit more precise, the problem is that sortable is trying to do an alias_method_chain call on an AR attribute while the setter for this attribute isn't defined yet. See line 148: https://github.com/shuber/sortable/blob/master/lib/sortable.rb#L148

The fix would be to load the columns calling #columns or #column_names to ensure that the setters are defined before calling the aliasing. In this case @mokolabs had to do that from within his code before calling sortable. He could have called self.columns or self.column_names, the point is that he has to trigger the mechanism fetching the table's columns and create the accessors so when the aliasing can take place without crashing.
- Matt

**Comment by mokolabs** [comment]
And here's an example of the crash output for those who are curious:
http://pastie.org/pastes/1277511
